# **Progetto di Digital Signal & Image Management**

## **Parte 2 - Image Classification - DEMO**

*2020/2021*

Peracchi Marco 800578

Uccheddu Christian 800428

In [1]:
import os
import numpy as np
from time import time
from scipy.io import wavfile as wav
import IPython.display as ipd

from PIL import Image

import matplotlib.pyplot as plt

import pandas as pd

from sklearn.preprocessing import scale

import cv2 as cv

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.applications import mobilenet
from sklearn.linear_model import LogisticRegression

In [2]:
model_1 = tf.keras.models.load_model('modello_immagini')

In [6]:
cap = cv.VideoCapture("test_3.avi")
start_time = time()
while (time() - start_time) < 50:
    _, frame = cap.read()

    #Convert the captured frame into RGB
    im = Image.fromarray(frame, 'RGB')

    #Resizing into 128x128 because we trained the model with this image size.
    im = im.resize((224,224))
    img_array = np.array(im)

    #Our keras model used a 4D tensor, (images x height x width x channel)
    #So changing dimension 128x128x3 into 1x128x128x3 
    
    img_array = np.expand_dims(img_array, axis=0)

    #Calling the predict method on model to predict 'me' on the image
    #prediction = int(model_1.predict(img_array)[0][0])
    prediction = model_1.predict(img_array)
    
    result = np.argmax(prediction, axis = 1)
    
    if result == 0:
        label = "No"
    else:
        label = "Yes"
    

    #if prediction is 0, which means I am missing on the image, then show the frame in gray color.
    
    text = "Emergency: {}{}".format(label, prediction)
    cv.putText(frame, text, (35, 50), cv.FONT_HERSHEY_SIMPLEX,
        1.25, (0, 255, 0), 5)

    cv.imshow("Capturing", frame)
    key=cv.waitKey(1)
    if key == ord('q'):
        break
        
cap.release()
cv.destroyAllWindows()

[[6.1091212e-17 1.3969539e-36]]
[[0.7941828 0.       ]]
[[1.3692086e-13 0.0000000e+00]]
[[1.7420531e-09 0.0000000e+00]]
[[2.9497946e-07 0.0000000e+00]]
[[6.940721e-13 0.000000e+00]]
[[6.1297256e-12 0.0000000e+00]]
[[1.241092e-08 0.000000e+00]]
[[2.4744253e-05 0.0000000e+00]]
[[0.0294305 0.       ]]
[[1.8946682e-19 3.2437451e-35]]
[[2.1413255e-15 0.0000000e+00]]
[[1.973253e-08 0.000000e+00]]
[[5.884169e-13 0.000000e+00]]
[[3.961338e-10 0.000000e+00]]
[[6.4042645e-15 1.9700339e-38]]
[[9.629221e-07 0.000000e+00]]
[[6.1243236e-13 0.0000000e+00]]
[[2.0496096e-19 1.7549074e-30]]
[[4.8746742e-22 4.5956486e-27]]
[[1.4734766e-19 0.0000000e+00]]
[[1.2071352e-18 0.0000000e+00]]
[[5.082049e-20 0.000000e+00]]
[[2.3665247e-17 0.0000000e+00]]
[[5.0394496e-25 0.0000000e+00]]
[[3.6300950e-19 1.0295857e-36]]
[[1.2836787e-21 1.5726807e-30]]
[[1.0586906e-24 1.6132788e-28]]
[[1.2078596e-16 1.7915206e-38]]
[[2.1964170e-22 1.1392262e-28]]
[[5.2542955e-23 3.8466595e-32]]
[[3.3652860e-29 2.6142656e-30]]
[[4.62

In [9]:
cap

<VideoCapture 0000027ACE94ADD0>

In [8]:
single_processing = keras.preprocessing.image.ImageDataGenerator(preprocessing_function= mobilenet.preprocess_input)

single_generator = single_processing.flow_from_directory("single",
                                    target_size = (224, 224),
                                    color_mode = "rgb",
                                    batch_size = 1,
                                    class_mode = "categorical",
                                    shuffle = False,
                                    seed = 1)
test,label_test = next(single_generator)

Found 1 images belonging to 1 classes.


In [14]:
model_1 = tf.keras.models.load_model('modello_audio')

In [15]:
model_1

In [16]:
test_features = model_1.predict(test)
test_features = test_features.reshape(test_features.shape[0],
                                      test_features.shape[1]*test_features.shape[2]*test_features.shape[3])

In [24]:
lr_1 = LogisticRegression(solver="lbfgs", multi_class="auto", max_iter=30, penalty ='l2', verbose = 1)
lr_1.fit(test_features, tf.argmax(y_train, axis=1))

NameError: name 'y_train' is not defined

In [23]:
pred_finali = lr_1.predict(test_features)

NotFittedError: This LogisticRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
pred_finali

In [ ]:
labels = (train_generator.class_indices)
labels = dict((v,k) for k,v in labels.items())
predictions = [labels[k] for k in pred_finali]

predictions